---

- name: install git, golang, and build-essential
  tags: git,golang,build-essential
  package:
    name:
      - git
      - golang
      - build-essential
    state: present
  become: true

- name: install nfs server
  tags: nfs,nfs-server
  package:
    name: nfs-kernel-server
    state: present
  become: true

# - name: clone k3s repo
#   tags: k3s
#   git:
#     repo: https://github.com/k3s-io/k3s-ansible
#     dest: /home/pi/repos/
#     clone: yes
#     update: yes
#     version: master
#   become: true

- name: download helm
  tags: helm
  unarchive:
    src: https://get.helm.sh/helm-v3.7.0-linux-arm.tar.gz
    dest: /home/pi
    remote_src: yes

- name: install helm
  tags: helm
  copy:
    src: /home/pi/linux-arm/helm
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  become: true