---

- name: change pi password
  user:
    name: "{{ usr }}"
    update_password: always
    password: "{{ password | password_hash('sha512') }}"
  become: true

- name: update password used
  set_fact: ansible_become_pass="{{ password }}"
  become: true

- name: update apt cache
  tags: always
  apt:
    update_cache: yes
  become: true

- name: create fileshare dir
  file:
    path: /mnt/storage
    state: directory
    owner: pi
    mode: 0755