---

- name: change pi password
  user:
    name: "{{ usr }}"
    update_password: always
    password: "{{ password | password_hash('sha512') }}"

- name: Update password used
  set_fact: ansible_become_pass="{{ password }}"

- name: update apt cache
  tags: always
  apt:
    update_cache: yes
  become: true

- name: update password used
  set_fact: ansible_become_pass="{{ password }}"