---

- name: change pi password
  become: true
  tags: firstrun,changepass
  user:
    name: "{{ usr }}"
    update_password: always
    password: "{{ password | password_hash('sha512') }}"

- name: update password used
  become: true
  tags: firstrun,changepass,storenewpass
  set_fact: ansible_become_pass="{{ password }}"

- name: change hostname
  become: true
  tags: hostname
  hostname:
    name: "{{ new_hostname }}"

- name: apply /etc/hosts template
  become: true
  tags: hosts
  ansible.builtin.template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

- name: send ansible ssh key
  tags: firstrun,sshkey
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', '/home/marc/.ssh/ansible.pub') }}"

- name: update apt cache
  become: true
  tags: always
  apt:
    update_cache: yes

- name: create fileshare dir
  become: true
  file:
    path: /mnt/storage
    state: directory
    owner: pi
    mode: 0755