---

- name: change pi password
  become: true
  tags: firstrun,changepass
  user:
    name: "{{ usr }}"
    update_password: always
    password: "{{ password | password_hash('sha512') }}"

- name: update password used
  become: true
  tags: firstrun,changepass,storenewpass
  set_fact: ansible_become_pass="{{ password }}"

- name: change hostname
  become: true
  tags: hostname
  hostname:
    name: "{{ new_hostname }}"

- name: fix /etc/hosts removing the old hostname
  become: true
  lineinfile:
    state=present
    dest=/etc/hosts
    line="{{ ansible_default_ipv4.address }} {{ inventory_hostname }}"
    regexp="^{{ ansible_default_ipv4.address }}"
  when:
    ansible_fqdn != inventory_hostname

- name: validate ansible_fqdn == inventory_hostname
  assert:
    that:
      ansible_fqdn == inventory_hostname

- name: send ansible ssh key
  tags: firstrun,sshkey
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', '/home/marc/.ssh/ansible.pub') }}"

- name: update apt cache
  become: true
  tags: always
  apt:
    update_cache: yes

- name: create fileshare dir
  become: true
  file:
    path: /mnt/storage
    state: directory
    owner: pi
    mode: 0755