---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: install apache2 packae
    apt: 
      name: apache2
      state: present
      when: ansible_distribution == "Debian"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: present
      when: ansible_distribution == "Debian"